[project]
name = "semantic-kernel-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.4",
    "numpy>=2.3.4",
    "openai>=2.8.0",
    "pydantic>=2.11.10",
    "semantic-kernel>=1.36.0",
]
